# SwiftLint Configuration for TENEX iOS
# Strict rules for professional, maintainable code

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - Tuist
  - Derived
  - .build
  - vendor
  - Project.swift  # Tuist DSL doesn't follow standard naming conventions
  - Tuist.swift

# Enabled rules
opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # We use expiring_todo instead
  - line_length # Configured below with warning/error thresholds
  - trailing_comma # SwiftFormat adds trailing commas, so we allow them
  - prefixed_toplevel_constant # Conflicts with common Swift patterns
  - type_contents_order # Conflicts with SwiftFormat organizeDeclarations
  - attributes # Conflicts with SwiftFormat attribute placement

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - to
    - at
    - by
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 60

# Force unwrapping is an error, not just a warning
force_unwrapping:
  severity: error

# Implicitly unwrapped optionals are an error
implicitly_unwrapped_optional:
  severity: error
  mode: all_except_iboutlets

# Force cast is an error
force_cast:
  severity: error

# Force try is an error
force_try:
  severity: error

# Large tuples
large_tuple:
  warning: 3
  error: 4

# Closure body length
closure_body_length:
  warning: 30
  error: 50

# Enum case associated values
enum_case_associated_values_count:
  warning: 5
  error: 6

# File header (require copyright)
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  TENEX
                    \/\/

# Type contents order
type_contents_order:
  order:
    - associated_type
    - type_alias
    - case
    - subtype
    - type_property
    - instance_property
    - ib_inspectable
    - ib_outlet
    - initializer
    - deinitializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript

# Modifier order
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutating
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# Expiring TODO - TODOs must have expiration dates
expiring_todo:
  approaching_expiry_severity: warning
  expired_severity: error
  date_format: "MM/dd/yyyy"
  date_delimiters:
    opening: "["
    closing: "]"
  date_separator: "/"
  approaching_expiry_threshold: 15

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use Logger instead of print statements"
    severity: warning

  no_hardcoded_strings_in_ui:
    name: "No Hardcoded UI Strings"
    regex: "Text\\(\"[^\"]+\"\\)"
    message: "Use localized strings for UI text"
    severity: warning
    match_kinds:
      - identifier

  prefer_async_await:
    name: "Prefer Async/Await"
    regex: "completionHandler|completion:\\s*@escaping"
    message: "Prefer async/await over completion handlers"
    severity: warning

reporter: "xcode"
